### ISSUE TITLE
Could you include the database tables?

### ISSUE THREAD

**Issue by desmith3** [karthikbangera87/Tutor_me#1]

**Comment by karthikbangera87** [comment]
Updated the repository

**Comment by desmith3** [comment]
hey how do I set up the email validation in this code?

On Mon, Nov 16, 2015 at 5:49 PM, Karthik notifications@github.com wrote:

> Closed #1 https://github.com/karthikbangera87/Tutor_me/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/karthikbangera87/Tutor_me/issues/1#event-466098993.

## 

_Darby Smith_
_Management Information Systems_
_University of Alabama_
_Roll Tide!_
